### ISSUE TITLE
why

### ISSUE THREAD

**Issue by Shrekfied** [jdev082/TgQXBcAGj6J-z-3t#2]
are you ok

**Comment by jdev082** [comment]
This was to comply with [this policy](https://github.com/JaydenDev/JaydenDev/blob/main/POL/SourcePosting.md).

**Comment by Shrekfied** [comment]
@JaydenDev i don't think doing all of that was necessary

**Comment by dinonull** [comment]
also making public policies or your self is why

**Comment by jdev082** [comment]
> also making public policies for your self is **_why_**

I didn't know what else to call it other than a policy.
